### ISSUE TITLE
Редактирование уведомлений

### ISSUE THREAD

**Issue by anry-das** [Katiktus/NCTaskManagerJava#17]
При попытке редактировать уведомления (6) выводится главное меню. Если ввести "y", то падает ошибка:
```
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:939)
	at java.base/java.util.Scanner.next(Scanner.java:1594)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2258)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2212)
	at ua.edu.sumdu.j2se.pohorila.cli.LoadManager.choice(LoadManager.java:49)
...
```

**Comment by Katiktus** [comment]
commit 069e4e241e03e6bdd02796299351b8efd0d31e7f
